#ZONE CLIENT
dash_homepage:
    path:     /
    defaults: { _controller: DashBundle:Category:index }
#soap_articles_list:
#    path:     /comptoir-client/articles-list
#    defaults: { _controller: DashBundle:Default:articlesList }
login_page:
    path:     /login
    defaults: { _controller: DashBundle:Default:login }
logout_page:
    path:     /logout
    defaults: { _controller: DashBundle:Default:logout }
categorys_list:
    path:     /comptoir-client/catalogue
    defaults: { _controller: DashBundle:Category:index }
category_single:
    path:     /comptoir-client/catalogue/{id}
    defaults: { _controller: DashBundle:Category:category }
category_single_products:
    path:     /comptoir-client/catalogue/{id}/articles
    defaults: { _controller: DashBundle:Default:filterArticles }
category_single_products_list:
    path:     /comptoir-client/catalogue/{id}/articles-list
    defaults: { _controller: DashBundle:Default:index }
category_product_result:
    path:     /comptoir-client/catalogue/{id}/result
    defaults: { _controller: DashBundle:Default:articleResult }

panier:
    path:     /panier
    defaults: { _controller: DashBundle:Panier:panier }
panier_top:
    path:     /comptoir-client/panier-top
    defaults: { _controller: DashBundle:Panier:panierTopHeader }
ajouter_produit:
    path:     /comptoir-client/ajouter-produit-ajx
    defaults: { _controller: DashBundle:Panier:panierTopHeaderAddProduct }
panier_invoice:
    path:     /comptoir-client/success/invoice
    defaults: { _controller: DashBundle:Panier:invoicePanier }
order_list:
    path:     /comptoir-client/orders
    defaults: { _controller: DashBundle:Panier:orderList }
update_article_qte:
    path:     /panier/update-qte-ajx
    defaults: { _controller: DashBundle:Panier:updateQteArticle }
#ZONE MANAGER

#ZONE ADMIN
admin_category_list:
    path: /administration/category/list
    defaults: { _controller: DashBundle:Category:adminCategoryList }
admin_category_add:
    path: /administration/category/add
    defaults: { _controller: DashBundle:Category:adminCategoryAdd }
admin_category_edit:
    path: /administration/category/edit/{id}
    defaults: { _controller: DashBundle:Category:adminCategoryEdit }
admin_category_delete:
    path: /administration/category/list/{id}
    defaults: { _controller: DashBundle:Category:adminCategoryDelete }
#Cron Clients
admin_cron_clients:
    path: /administration/cron/clients
    defaults: { _controller: DashBundle:CronArticlesReload:cronClients }

#ZONE VALIDATEUR
validateur_list_clients:
    path: /validateur/list-clients
    defaults: { _controller: DashBundle:Validateur:clientsList }
validateur_list_commands:
    path: /validateur/list-commands
    defaults: { _controller: DashBundle:Validateur:commandList }