#front_homepage:
#    path:     /
#    defaults: { _controller: FrontBundle:Default:index }

global_articles_result:
    path: /articles/{category}/page/{page}
    defaults: { _controller: FrontBundle\Controller\ArticlesController::globalArticlesAction }

articles_result:
    path: /api/{catRef}/{page}
    defaults: { _controller: FrontBundle\Controller\ArticlesController::articleResultAction }

single_article_result:
    path: /article/{tcateg}/{tsouscateg}/{ref}
    defaults: { _controller: FrontBundle\Controller\ArticlesController::apercuRapideAction }

contact:
    path: /contact
    defaults: { _controller: FrontBundle\Controller\ContactController::contactAction }

favoris:
    path: /favoris
    defaults: { _controller: FrontBundle\Controller\FavorisController::favorisAction }

pre_searrch:
    path: /presearch
    defaults: { _controller: FrontBundle\Controller\SearchController::preSearchContainerAction }

search:
    path: /search/{query}/{page}
    defaults: { _controller: FrontBundle\Controller\SearchController::searchContainerAction }

#Client Account Routing
compte_client:
    path: /espace-client
    defaults: { _controller: FrontBundle\Controller\CompteClientController::mainAccountAction }
apercu_rapide_ajx:
    path: /apercu-rapide-ajx
    defaults: { _controller: FrontBundle\Controller\ArticlesController::apercuRapideAction }
facture_detail_ajx:
    path: /facture-detail-ajx
    defaults: { _controller: FrontBundle\Controller\PanierController::generatePdfInvoiceAction }
