services:
  app.file.twig.extension:
    class: %app.file.twig.extension.class%
    tags:
      - { name: twig.extension }
#    front.example:
#        class: FrontBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
