services:
  front.twig_extension:
    class: FrontBundle\Twig\Extension\FileExtension
    tags:
      - { name: twig.extension }
#    front.example:
#        class: FrontBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
