dashboard_admin_homepage:
  path:     /
  defaults: {_controller: AdminBundle:Settings:settings}

admin_parameters_list:
  path: /parameters
  defaults: {_controller: AdminBundle:Settings:settings}
#ZONE ADMIN
admin_category_list:
  path: /category/list
  defaults: { _controller: DashBundle:Category:adminCategoryList }
admin_category_add:
  path: /category/add
  defaults: { _controller: DashBundle:Category:adminCategoryAdd }
admin_category_edit:
  path: /category/edit/{id}
  defaults: { _controller: DashBundle:Category:adminCategoryEdit }
admin_category_delete:
  path: /category/list/{id}
  defaults: { _controller: DashBundle:Category:adminCategoryDelete }
#Slider Routers
upload_slider:
  path: /slider/uploadajx
  defaults: { _controller: AdminBundle:Slider:uploadInit }
list_slider:
  path: /slider/manage
  defaults: { _controller: AdminBundle:Slider:sliderManage }
remove_slider:
  path: /slider/remove
  defaults: { _controller: AdminBundle:Slider:removeSlider }

#Ads Routers
upload_ads:
  path: /ads/uploadajx
  defaults: { _controller: AdminBundle:Ads:uploadInit }
list_ads:
  path: /ads/manage
  defaults: { _controller: AdminBundle:Ads:adsManage }
remove_ads:
  path: /ads/remove
  defaults: { _controller: AdminBundle:Ads:removeAds }
#Marques Routers
upload_marque:
  path: /marques/uploadajx
  defaults: { _controller: AdminBundle:Marques:uploadInit }
list_marques:
  path: /marques/manage
  defaults: { _controller: AdminBundle:Marques:marquesManage }
remove_marque:
  path: /marques/remove
  defaults: { _controller: AdminBundle:Marques:removeMarques }
#Cron Clients
admin_cron_clients:
  path: /cron/clients
  defaults: { _controller: DashBundle:CronArticlesReload:cronClients }