admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /cotupap-admin133785

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

dash:
    resource: "@DashBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

soap_test:
    path: /soap-service
    defaults: {_controller: AppBundle:Default:soap}

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#    prefix:   /cotupap-admin133785

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"