# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_VALIDATEUR: ROLE_VALIDATEUR

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            user_checker: security.user_checker
            form_login:
                provider:               fos_userbundle
                login_path:             fos_user_security_login
                check_path:             fos_user_security_check
#                check_path:             /login_check
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/cotupap-admin133785/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cotupap-admin133785/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cotupap-admin133785/, role: ROLE_ADMIN }
        - { path: ^/validateur/, role: ROLE_VALIDATEUR }