<?php

namespace FrontBundle\Repository;

/**
 * DetcmdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetcmdRepository extends \Doctrine\ORM\EntityRepository
{
}
